doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # Provide a default server_version to avoid InvalidPlatformVersion when env is missing
        server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            Account:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Account/Entity'
                prefix: 'App\Domain\Account\Entity'
                alias: Account
            Equipment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Equipment/Entity'
                prefix: 'App\Domain\Equipment\Entity'
                alias: Equipment
            Reservation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Reservation/Entity'
                prefix: 'App\Domain\Reservation\Entity'
                alias: Reservation
            ReleaseReturn:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/ReleaseReturn/Entity'
                prefix: 'App\Domain\ReleaseReturn\Entity'
                alias: ReleaseReturn
            Venue:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Venue/Entity'
                prefix: 'App\Domain\Venue\Entity'
                alias: Venue
            Task:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Task/Entity'
                prefix: 'App\Domain\Task\Entity'
                alias: Task
            AuditLog:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/AuditLog/Entity'
                prefix: 'App\Domain\AuditLog\Entity'
                alias: AuditLog
            Notification:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Notification/Entity'
                prefix: 'App\Domain\Notification\Entity'
                alias: Notification
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
